
package com.perso.proj.mapred.ws.serviceinterf.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.6
 * Mon May 25 15:16:20 EDT 2020
 * Generated source version: 3.3.6
 */

@XmlRootElement(name = "combine", namespace = "http://serviceinterf.ws.mapred.proj.perso.com")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "combine", namespace = "http://serviceinterf.ws.mapred.proj.perso.com", propOrder = {"arg0", "arg1"})

public class Combine {

    @XmlElement(name = "arg0")
    private java.util.HashMap<java.lang.String, java.lang.Integer> arg0;
    @XmlElement(name = "arg1")
    private java.util.HashMap<java.lang.String, java.lang.Integer> arg1;

    public java.util.HashMap<java.lang.String, java.lang.Integer> getArg0() {
        return this.arg0;
    }

    public void setArg0(java.util.HashMap<java.lang.String, java.lang.Integer> newArg0)  {
        this.arg0 = newArg0;
    }

    public java.util.HashMap<java.lang.String, java.lang.Integer> getArg1() {
        return this.arg1;
    }

    public void setArg1(java.util.HashMap<java.lang.String, java.lang.Integer> newArg1)  {
        this.arg1 = newArg1;
    }

}

