
package com.perso.proj.serviceinterf.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.9
 * Tue May 12 10:11:18 EDT 2020
 * Generated source version: 2.7.9
 */

@XmlRootElement(name = "convertF2C", namespace = "http://serviceinterf.proj.perso.com")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "convertF2C", namespace = "http://serviceinterf.proj.perso.com")

public class ConvertF2C {

    @XmlElement(name = "arg0")
    private int arg0;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

}

